dist: trusty
sudo: required

services:
  - docker
#env:
#  global:
#  - secure: "AzM98HKS2RDP+/WdvsFiEqTbVPwLBEAtNXDQPR7cV1gAEZoNhri/iINnRAHtECgVQDt2gKmxEiyOA07zMKPpt5PwhoyZUnICwxl1t2FOkTL4LlfI+3ew1rf4F8wmaSQX/BRT7b3IgyEI0RFRCow8KH49X8xdEtAFYJB3YFu2Y6M="
#  - secure: "BDNmD9y3mdZEQoFgXW2dC1FawofkThFwbITidMqeKLxSstNxQGKCpxOFAV604kaTGsf7ihpdm8WYE5IjHKTaoewdQ9hLXZPtswWXq5Ebe2gKHqJVNZa2bFD6hQBD2S7BLWWeAVIoLkyfV/QLnplOquUZTXWZ3TW2A+IXzQE+AnE="
language: java
jdk: oraclejdk8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ant
#    - gcc-6
#    - g++-6
    - oracle-java8-installer
#    - xorg-dev
#    - libgtk-3-dev

before_install:
- pip install --user awscli
- docker pull intrigus/docker-raspberry-pi-cross-compiler
- docker run intrigus/docker-raspberry-pi-cross-compiler > ~/bin/rpxc
- chmod +x ~/bin/rpxc
- export PATH=$PATH:$HOME/bin:$HOME/.local/bin
- export RPXC_IMAGE=intrigus/docker-raspberry-pi-cross-compiler

script:
- echo "LWJGL_BUILD_TYPE=nightly" >> .lwjgl_env_rpxc
#- echo "LWJGL_BUILD_OFFLINE=true" >> .lwjgl_env_rpxc
- echo "LWJGL_BUILD_ARCH=armv6" >> .lwjgl_env_rpxc
- LWJGL_BUILD_SYSROOT=$(rpxc sh -c 'echo $SYSROOT')
- echo "LWJGL_BUILD_SYSROOT=$LWJGL_BUILD_SYSROOT" >> .lwjgl_env_rpxc
- echo "PKG_CONFIG_DIR=" >> .lwjgl_env_rpxc
- echo "PKG_CONFIG_LIBDIR=${LWJGL_BUILD_SYSROOT}/usr/lib/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/share/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/share/arm-linux-gnueabihf/pkgconfig" | tee .lwjgl_env_rpxc
- echo "PKG_CONFIG_SYSROOT_DIR=$LWJGL_BUILD_SYSROOT" >> .lwjgl_env_rpxc
- cat .lwjgl_env_rpxc
#- export 
- rpxc --args "--env-file .lwjgl_env_rpxc" bash -c 'pkg-config --debug gtk+-3.0 && printenv && ant -debug -DtoolPrefix=arm-linux-gnueabihf- compile-templates tests'
# upload-native
